### ISSUE TITLE
No pr-aduit-group.txt file mentioned by the bot

### ISSUE THREAD

**Issue by kbumsik** [nnstreamer/TAOS-CI#637]
# Issue Description
While I posted a PR https://github.com/nnstreamer/nnstreamer/pull/2714 I noticed there is no `pr-aduit-group.txt` link triggered when a build failed.

The relevant code looks like these but I am not sure which file link is supposed to be instead.

https://github.com/nnstreamer/TAOS-CI/blob/5ee8727b367c42d4d00bd933767f0d09b316618d/ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh#L202

https://github.com/nnstreamer/TAOS-CI/blob/5ee8727b367c42d4d00bd933767f0d09b316618d/ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh#L425

How to Reproduce
===============
1. Go to https://github.com/nnstreamer/nnstreamer/pull/2714
2. Click `pr-audiot-group.txt` mentioned by the bot: https://github.com/nnstreamer/nnstreamer/pull/2714#issuecomment-690082460
3. 404 Error
![image](https://user-images.githubusercontent.com/7823583/92704518-f7b51700-f38d-11ea-87f3-bc08f56fa443.png)

**Comment by gichan-jang** [comment]
Let's remove `/pr-aduit-group.txt`.
