### ISSUE TITLE
Let's check if the ./packaing/.gbs.conf  file exists or not

### ISSUE THREAD

**Issue by leemgs** [nnstreamer/TAOS-CI#695]
In order to support a customized repository environment, 
let's append a routine to check if the ./packaing/.gbs.conf file exists or not.

**Comment by leemgs** [comment]
## Test Scenario

ubuntu$ time gbs -c ./packaging/.gbs.conf build -A armv7l --inclue-all --clean

**Comment by gichan-jang** [comment]
After #697 , I checked two problems.
```
[DEBUG] Checking if the ./.TAOS-CI/.gbs.conf file exists or not.
[DEBUG] Oooops. We could not find anyone among the below three gbs configuration files.
[DEBUG] Please ask an administrator of CI server on this issue.
[DEBUG] ./.TAOS-CI/.gbs.conf
[DEBUG] ./packaging/.gbs.conf
[DEBUG] /.gbs.conf
[DEBUG] Running...
```

1. Default gbs config path is incorrect.

*[DEBUG] /.gbs.conf* -> **/var/www/html/.gbs.conf**

2. If all three gbs config files are missing, the run queue is stopped.

**Comment by myungjoo** [comment]
Close if resolved.
